/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hms;
import java.util.*;
import java.sql.*;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author manik-pc
 */
public class Pregistation extends javax.swing.JFrame {

    //Connection conn=null;
   // private Object Connect;
    public Pregistation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(675, 525));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 102));
        jLabel2.setText("PATIENT REGISTRATION:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 20, 320, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 255));
        jLabel3.setText("Patient Information:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(24, 80, 150, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 255, 0));
        jLabel4.setText("No:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 150, 90, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 255, 0));
        jLabel5.setText("Date:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 210, 90, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 255, 0));
        jLabel6.setText("Name:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 270, 90, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 255, 0));
        jLabel7.setText("Father's Name:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 330, 90, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 255, 0));
        jLabel8.setText("Sex:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 394, 80, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 255, 0));
        jLabel9.setText("Age:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 450, 90, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 255, 0));
        jLabel10.setText("Phone No:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(380, 144, 90, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 255, 0));
        jLabel11.setText("Address:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(380, 204, 90, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 51, 51));
        jLabel12.setText("Consulting Doctor Name:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(300, 264, 180, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 255, 0));
        jLabel13.setText("Room No:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(380, 324, 90, 30);

        jTextField1.setForeground(new java.awt.Color(0, 51, 153));
        getContentPane().add(jTextField1);
        jTextField1.setBounds(120, 140, 150, 40);

        jTextField2.setForeground(new java.awt.Color(0, 51, 153));
        getContentPane().add(jTextField2);
        jTextField2.setBounds(120, 210, 160, 40);

        jTextField3.setForeground(new java.awt.Color(0, 51, 153));
        getContentPane().add(jTextField3);
        jTextField3.setBounds(120, 270, 160, 40);

        jTextField4.setForeground(new java.awt.Color(0, 51, 153));
        getContentPane().add(jTextField4);
        jTextField4.setBounds(119, 330, 160, 40);

        jTextField5.setForeground(new java.awt.Color(0, 51, 153));
        getContentPane().add(jTextField5);
        jTextField5.setBounds(120, 440, 130, 40);

        jTextField6.setForeground(new java.awt.Color(0, 51, 153));
        getContentPane().add(jTextField6);
        jTextField6.setBounds(490, 140, 150, 40);

        jTextField7.setForeground(new java.awt.Color(0, 51, 153));
        getContentPane().add(jTextField7);
        jTextField7.setBounds(489, 200, 150, 40);

        jTextField8.setForeground(new java.awt.Color(0, 51, 153));
        getContentPane().add(jTextField8);
        jTextField8.setBounds(490, 260, 150, 40);

        jTextField9.setForeground(new java.awt.Color(0, 51, 153));
        getContentPane().add(jTextField9);
        jTextField9.setBounds(490, 320, 150, 40);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(120, 390, 110, 40);

        jSeparator1.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(160, 100, 170, 10);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 153, 0));
        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(310, 430, 100, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 153, 0));
        jButton2.setText("RESET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(430, 430, 90, 40);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(153, 153, 0));
        jButton3.setText("BACK");
        getContentPane().add(jButton3);
        jButton3.setBounds(540, 430, 80, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/maincover11.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 680, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String idno = jTextField1.getText();
        String date = jTextField2.getText();
       String name = jTextField3.getText();
       String fathername = jTextField4.getText();
       String sex = jComboBox1.getSelectedItem().toString();
       String age = jTextField5.getText();
       String phoneno = jTextField6.getText();
       String address = jTextField7.getText();
       String condocname = jTextField8.getText();
       String roomno = jTextField9.getText();
        
        
        
        ResultSet rs=null;
        PreparedStatement ps=null;
        String k=new String();
       // q="Insert into patientreg2 values('"+idno+"','"+date+"','"+name+"','"+fathername+"','"+sex+"','"+age+"','"+phoneno+"','"+address+"','"+condocname+"','"+roomno+"')";
       try{
          // System.out.print("manik");
          /*if (jTextField1.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Please enter user id!","Error", JOptionPane.ERROR_MESSAGE);
           return;
           }
           if (jTextField2.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Please enter user name!","Error", JOptionPane.ERROR_MESSAGE);
           return;
           }
           
           if (jTextField3.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Please enter user address1!","Error", JOptionPane.ERROR_MESSAGE);
           return;
           }
           if (jTextField4.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Please enter user contact no!","Error", JOptionPane.ERROR_MESSAGE);
           return;
           }
           if (jTextField5.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Please enter user security key!","Error", JOptionPane.ERROR_MESSAGE);
           return;
           }
           if (jComboBox1.getSelectedItem().toString().equals("")) {
           JOptionPane.showMessageDialog( this, "Please enter user gender!","Error", JOptionPane.ERROR_MESSAGE);
           return;
           }
           if (jTextField6.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Please enter user type!","Error", JOptionPane.ERROR_MESSAGE);
           return;
           }
           if (jTextField7.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Please enter user type!","Error", JOptionPane.ERROR_MESSAGE);
           return;
           }
           if (jTextField8.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Please enter user type!","Error", JOptionPane.ERROR_MESSAGE);
           return;
           }
           if (jTextField9.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Please enter user type!","Error", JOptionPane.ERROR_MESSAGE);
           return;
           }*/
            k="Insert into patientreg2 values('"+idno+"','"+date+"','"+name+"','"+fathername+"','"+sex+"','"+age+"','"+phoneno+"','"+address+"','"+condocname+"','"+roomno+"')";
            ps=conn.prepareStatement(k);
            ps.execute();
            System.out.print("Manik");
            JOptionPane.showMessageDialog(null,"Registration Successfull");
            
        }catch(Exception e){
          JOptionPane.showMessageDialog(null,"Patient Registration Fail");
        }
    }//GEN-LAST:event_jButton1ActionPerformed
 private void formWindowOpened(java.awt.event.WindowEvent evt) {                                  
       conn = Sqlite.ConnectDB();
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       jTextField1.setText("");
       jTextField3.setText("");
       jTextField2.setText("");
       jTextField4.setText("");
       jTextField6.setText("");
       jTextField7.setText("");
       jTextField5.setText("");
       jTextField8.setText("");
       jTextField9.setText("");
       
    }//GEN-LAST:event_jButton2ActionPerformed

   public Connection conn = null;
   

    // public String idno = new String();
   // public String date = new String();
   // public String name = new String();
   // public String fathername = new String();
   // public String sex = new String();
   // public String age = new String();
   // public String phoneno = new String();
   // public String address = new String();
   // public String condocname = new String();
   // public String roomno = new String();
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pregistation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pregistation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pregistation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pregistation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pregistation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
